using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace GodotLogger.Generator;

[Generator]
public sealed class GodotLoggerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "GodotLogger.GodotLoggerAttribute";
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace GodotLogger
        {
            /// <summary>
            ///     Controls the access modifier of the generated logger field.
            /// </summary>
            internal enum LoggerAccessibility
            {
                /// <summary>The field is <c>private</c> (default).</summary>
                Private,
                /// <summary>The field is <c>protected</c>.</summary>
                Protected,
                /// <summary>The field is <c>internal</c>.</summary>
                Internal,
                /// <summary>The field is <c>public</c>.</summary>
                Public,
            }

            /// <summary>
            ///     Automatically adds the GodotLogger via source generation.
            /// </summary>
            /// <remarks>
            ///     The annotated class <b>must</b> be declared as <c>partial</c>.
            /// </remarks>
            /// <para>
            ///     The field name defaults to <c>Logger</c> and can be changed via <see cref="FieldName"/>.
            /// </para>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class GodotLoggerAttribute : global::System.Attribute
            {
                /// <summary>
                ///     Gets or sets the name of the generated logger field.
                ///     Defaults to <c>"Logger"</c>.
                /// </summary>
                public string FieldName { get; set; } = "Logger";

                /// <summary>
                ///     Gets or sets an explicit category name for the logger.
                ///     When set, the field type is <c>ILogger</c> and the factory call becomes
                ///     <c>GodotLog.CreateLogger("Category")</c>.
                ///     When <see langword="null"/> (default), the field type is <c>ILogger&lt;T&gt;</c>
                ///     and the factory call becomes <c>GodotLog.CreateLogger&lt;T&gt;()</c>.
                /// </summary>
                public string? Category { get; set; }

                /// <summary>
                ///     Gets or sets the access modifier of the generated logger field.
                ///     Defaults to <see cref="LoggerAccessibility.Private"/>.
                /// </summary>
                public LoggerAccessibility Accessibility { get; set; } = LoggerAccessibility.Private;
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Emit GodotLoggerAttribute into the compilation
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GodotLoggerAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // Per-class incremental pipeline: each class is processed independently so that
        // an edit to one file does not invalidate code generation for all other classes.
        var classDeclarations = context
            .SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) => GetClassIfAnnotated(ctx)
            )
            .Where(static c => c is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
            Execute(source.Left, source.Right, spc));
    }

    /// <summary>
    ///     Returns the class declaration if it carries [GodotLogger] otherwise <see langword="null" />.
    /// </summary>
    private static ClassDeclarationSyntax? GetClassIfAnnotated(GeneratorSyntaxContext ctx)
    {
        var classDeclaration = (ClassDeclarationSyntax)ctx.Node;

        var hasAttribute = classDeclaration.AttributeLists
            .SelectMany(list => list.Attributes)
            .Select(attr => ctx.SemanticModel.GetSymbolInfo(attr).Symbol)
            .OfType<IMethodSymbol>()
            .Any(ctor => ctor.ContainingType.ToDisplayString() == AttributeFullName);

        return hasAttribute ? classDeclaration : null;
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax?> classes,
        SourceProductionContext spc)
    {
        if (classes.IsDefaultOrEmpty)
            return;

        var attrSymbol = compilation.GetTypeByMetadataName(AttributeFullName);
        if (attrSymbol is null)
            return;

        foreach (var classDeclaration in classes.Distinct())
        {
            if (classDeclaration is null)
                continue;

            var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol) continue;

            var attrData = classSymbol.GetAttributes()
                .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol));
            if (attrData is null) continue;

            var fieldName = attrData.NamedArguments
                .FirstOrDefault(arg => arg.Key == "FieldName").Value.Value as string
                ?? "Logger";

            var category = attrData.NamedArguments
                .FirstOrDefault(arg => arg.Key == "Category").Value.Value as string;

            // LoggerAccessibility enum: 0=Private, 1=Protected, 2=Internal, 3=Public
            var accessibilityValue = attrData.NamedArguments
                .FirstOrDefault(arg => arg.Key == "Accessibility").Value.Value;
            var accessibility = accessibilityValue is int intVal ? intVal : 0;

            var source = GenerateSource(classSymbol, fieldName, category, accessibility);
            var hintName = $"{classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", "")
                .Replace("<", "_").Replace(">", "_")
                .Replace(",", "_").Replace(" ", "")}.GodotLogger.g.cs";

            spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateSource(INamedTypeSymbol classSymbol, string fieldName, string? category, int accessibility)
    {
        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        var className = classSymbol.Name;

        var ns = namespaceName is not null ? $"\nnamespace {namespaceName};\n" : "";

        var accessModifier = accessibility switch
        {
            1 => "protected",
            2 => "internal",
            3 => "public",
            _ => "private",
        };

        string fieldType;
        string factoryCall;
        if (category is not null)
        {
            fieldType = "ILogger";
            factoryCall = $"GodotLog.CreateLogger(\"{category}\")";
        }
        else
        {
            fieldType = $"ILogger<{className}>";
            factoryCall = $"GodotLog.CreateLogger<{className}>()";
        }

        return $$"""
            // <auto-generated/>
            #nullable enable
            using GodotLogger;
            using Microsoft.Extensions.Logging;
            {{ns}}
            partial class {{className}}
            {
                {{accessModifier}} static readonly {{fieldType}} {{fieldName}} =
                    {{factoryCall}};
            }
            """;
    }
}
